# nav2_params.yaml

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.22
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 2.5
      # Critic plugins needed for DWB
      critics:
        - RotateToGoal
        - Oscillation
        - ObstacleFootprint
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugin_ids: ["GridBased"]
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]

    GridBased:
      use_astar: false
      allow_unknown: true
      default_tolerance: 0.5

bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_bt_xml_filename: "navigate_w_replanning_and_recovery_nodes.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: false

velocity_smoother:
  ros__parameters:
    use_sim_time: false

behavior_server:
  ros__parameters:
    use_sim_time: false

smoother_server:
  ros__parameters:
    use_sim_time: false

# Global costmap
global_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    robot_radius: 0.15
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      map_subscribe_transient_local: True

    obstacle_layer:
      observation_sources: "scan"
      scan:
        topic: "/scan"
        max_obstacle_height: 1.0
        clearing: True
        marking: True

    inflation_layer:
      inflation_radius: 0.55

# Local costmap
local_costmap:
  ros__parameters:
    use_sim_time: false
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    robot_radius: 0.15
    rolling_window: True
    width: 3.0
    height: 3.0
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      map_subscribe_transient_local: True

    obstacle_layer:
      observation_sources: "scan"
      scan:
        topic: "/scan"
        max_obstacle_height: 1.0
        clearing: True
        marking: True

    inflation_layer:
      inflation_radius: 0.55
