slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: "mapping"
    base_frame: "laser_frame"
    odom_frame: "odom"
    map_frame: "map"
    transform_tolerance: 2.0  # You might try increasing to 2.0 or 5.0 seconds temporarily
    scan_topic: "scan"
    resolution: 0.05
    max_laser_range: 12.0
    minimum_score: 0.3  # Adjust this value if necessary
    publish_period_sec: 1.0
    update_period_sec: 5.0
